# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zeus-api}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Peterson"]
  s.date = %q{2010-11-25}
  s.description = %q{This gem implements a wrapper to the SOAP control API provided by Zeus Load Balancer (ZLB) and Zeus Traffic Manager (ZTM).}
  s.email = %q{peterson@orbitec.com.au}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/api/catalogrule/CatalogRule.rb",
    "lib/api/catalogrule/CatalogRuleClient.rb",
    "lib/api/catalogrule/CatalogRuleDriver.rb",
    "lib/api/catalogrule/CatalogRuleMappingRegistry.rb",
    "lib/api/catalogrule/CatalogRuleService.rb",
    "lib/api/pool/Pool.rb",
    "lib/api/pool/PoolClient.rb",
    "lib/api/pool/PoolDriver.rb",
    "lib/api/pool/PoolMappingRegistry.rb",
    "lib/api/pool/PoolService.rb",
    "lib/api/virtualserver/VirtualServer.rb",
    "lib/api/virtualserver/VirtualServerClient.rb",
    "lib/api/virtualserver/VirtualServerDriver.rb",
    "lib/api/virtualserver/VirtualServerMappingRegistry.rb",
    "lib/api/virtualserver/VirtualServerService.rb",
    "lib/zeus-api.rb",
    "sample/simple.rb",
    "spec/spec_helper.rb",
    "spec/virtualserver_spec.rb",
    "zeus-api.gemspec"
  ]
  s.homepage = %q{http://github.com/peterson/zeus-api}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby control API for Zeus Load Balancer and Zeus Traffic Manager}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/virtualserver_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<soap4r>, [">= 1.5.8"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<soap4r>, [">= 1.5.8"])
      s.add_development_dependency(%q<rspec>, ["> 1.2.3"])
    else
      s.add_dependency(%q<soap4r>, [">= 1.5.8"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<soap4r>, [">= 1.5.8"])
      s.add_dependency(%q<rspec>, ["> 1.2.3"])
    end
  else
    s.add_dependency(%q<soap4r>, [">= 1.5.8"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<soap4r>, [">= 1.5.8"])
    s.add_dependency(%q<rspec>, ["> 1.2.3"])
  end
end

