require 'VirtualServer.rb'
require 'VirtualServerMappingRegistry.rb'
require 'soap/rpc/driver'

class VirtualServerPort < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "https://admin_server:9090/soap"
  NsVirtualServer = "http://soap.zeus.com/zxtm/1.0/VirtualServer/"

  Methods = [
    [ XSD::QName.new(NsVirtualServer, "addCompressionMIMETypes"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/addCompressionMIMETypes",
      "addCompressionMIMETypes",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "addResponseRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/addResponseRules",
      "addResponseRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "rules", ["VirtualServerRuleArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RuleArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "addRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/addRules",
      "addRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "rules", ["VirtualServerRuleArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RuleArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "addSSLClientCertificateAuthorities"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/addSSLClientCertificateAuthorities",
      "addSSLClientCertificateAuthorities",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "addSSLSites"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/addSSLSites",
      "addSSLSites",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "ssl_sites", ["VirtualServerSSLSiteArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLSiteArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "addVirtualServer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/addVirtualServer",
      "addVirtualServer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "info", ["VirtualServerBasicInfoArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.BasicInfoArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "copyVirtualServer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/copyVirtualServer",
      "copyVirtualServer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "new_names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "deleteSSLSites"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/deleteSSLSites",
      "deleteSSLSites",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "site_ips", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "deleteVirtualServer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/deleteVirtualServer",
      "deleteVirtualServer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "editSSLSites"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/editSSLSites",
      "editSSLSites",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "site_ips", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]],
        ["in", "ssl_sites", ["VirtualServerSSLSiteArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLSiteArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getAddClusterClientIPHeader"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getAddClusterClientIPHeader",
      "getAddClusterClientIPHeader",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getBandwidthClass"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getBandwidthClass",
      "getBandwidthClass",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getBasicInfo"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getBasicInfo",
      "getBasicInfo",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "info", ["VirtualServerBasicInfoArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.BasicInfoArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCompressUnknownSize"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCompressUnknownSize",
      "getCompressUnknownSize",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCompressionEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCompressionEnabled",
      "getCompressionEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCompressionLevel"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCompressionLevel",
      "getCompressionLevel",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCompressionMIMETypes"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCompressionMIMETypes",
      "getCompressionMIMETypes",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCompressionMaxSize"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCompressionMaxSize",
      "getCompressionMaxSize",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCompressionMinSize"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCompressionMinSize",
      "getCompressionMinSize",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getConnectTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getConnectTimeout",
      "getConnectTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCookieDomainRewriteMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCookieDomainRewriteMode",
      "getCookieDomainRewriteMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerCookieDomainRewriteModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.CookieDomainRewriteModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCookieNamedDomain"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCookieNamedDomain",
      "getCookieNamedDomain",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCookiePathRewrite"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCookiePathRewrite",
      "getCookiePathRewrite",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerRegexReplacementArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RegexReplacementArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getCookieSecureFlagRewriteMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getCookieSecureFlagRewriteMode",
      "getCookieSecureFlagRewriteMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerCookieSecureFlagRewriteModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.CookieSecureFlagRewriteModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getDefaultPool"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getDefaultPool",
      "getDefaultPool",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getEnabled",
      "getEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getFTPDataSourcePort"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getFTPDataSourcePort",
      "getFTPDataSourcePort",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getFTPForceClientSecure"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getFTPForceClientSecure",
      "getFTPForceClientSecure",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getFTPForceServerSecure"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getFTPForceServerSecure",
      "getFTPForceServerSecure",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getFTPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getFTPPortRange",
      "getFTPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "range", ["VirtualServerFTPPortRangeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.FTPPortRangeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getFTPSSLData"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getFTPSSLData",
      "getFTPSSLData",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getKeepalive"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getKeepalive",
      "getKeepalive",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getKeepaliveTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getKeepaliveTimeout",
      "getKeepaliveTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getListenAddresses"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getListenAddresses",
      "getListenAddresses",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "addresses", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getListenOnAllAddresses"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getListenOnAllAddresses",
      "getListenOnAllAddresses",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getListenTrafficIPGroups"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getListenTrafficIPGroups",
      "getListenTrafficIPGroups",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "groups", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getLocationDefaultRewriteMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getLocationDefaultRewriteMode",
      "getLocationDefaultRewriteMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerLocationDefaultRewriteModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.LocationDefaultRewriteModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getLocationRewrite"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getLocationRewrite",
      "getLocationRewrite",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerRegexReplacementArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RegexReplacementArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getLogEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getLogEnabled",
      "getLogEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getLogFilename"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getLogFilename",
      "getLogFilename",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getLogFormat"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getLogFormat",
      "getLogFormat",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getMIMEAutoDetect"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getMIMEAutoDetect",
      "getMIMEAutoDetect",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getMIMEDefaultType"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getMIMEDefaultType",
      "getMIMEDefaultType",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getMaxClientBuffer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getMaxClientBuffer",
      "getMaxClientBuffer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getMaxServerBuffer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getMaxServerBuffer",
      "getMaxServerBuffer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getPort"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getPort",
      "getPort",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getProtection"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getProtection",
      "getProtection",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getProtocol"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getProtocol",
      "getProtocol",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerProtocolArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.ProtocolArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getProxyClose"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getProxyClose",
      "getProxyClose",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getRTSPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getRTSPPortRange",
      "getRTSPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "range", ["VirtualServerPortRangeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.PortRangeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getResponseRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getResponseRules",
      "getResponseRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "rules", ["VirtualServerRuleArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RuleArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getRewriteSIPURI"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getRewriteSIPURI",
      "getRewriteSIPURI",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getRules",
      "getRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "rules", ["VirtualServerRuleArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RuleArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSIPDangerousRequestMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSIPDangerousRequestMode",
      "getSIPDangerousRequestMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerSIPDangerousRequestModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SIPDangerousRequestModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSIPMaxConnectionMemory"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSIPMaxConnectionMemory",
      "getSIPMaxConnectionMemory",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSIPMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSIPMode",
      "getSIPMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerSIPModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SIPModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSIPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSIPPortRange",
      "getSIPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "range", ["VirtualServerPortRangeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.PortRangeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSIPStreamingTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSIPStreamingTimeout",
      "getSIPStreamingTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLCertificate"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLCertificate",
      "getSSLCertificate",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "certs", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLClientCertificateAuthorities"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLClientCertificateAuthorities",
      "getSSLClientCertificateAuthorities",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLClientCertificateHeaders"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLClientCertificateHeaders",
      "getSSLClientCertificateHeaders",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerSSLClientCertificateHeadersArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLClientCertificateHeadersArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLDecrypt"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLDecrypt",
      "getSSLDecrypt",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLExpectStartTLS"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLExpectStartTLS",
      "getSSLExpectStartTLS",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLHeaders"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLHeaders",
      "getSSLHeaders",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLLogEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLLogEnabled",
      "getSSLLogEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLRequestClientCertMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLRequestClientCertMode",
      "getSSLRequestClientCertMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["VirtualServerSSLRequestClientCertModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLRequestClientCertModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLSendCloseAlerts"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLSendCloseAlerts",
      "getSSLSendCloseAlerts",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLSites"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLSites",
      "getSSLSites",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "ssl_sites", ["VirtualServerSSLSiteArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLSiteArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSSLTrustMagic"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSSLTrustMagic",
      "getSSLTrustMagic",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getServerfirstBanner"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getServerfirstBanner",
      "getServerfirstBanner",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getServiceLevelMonitoring"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getServiceLevelMonitoring",
      "getServiceLevelMonitoring",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getSipTransactionTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getSipTransactionTimeout",
      "getSipTransactionTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getTimeout",
      "getTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getUDPResponseDatagramsExpected"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getUDPResponseDatagramsExpected",
      "getUDPResponseDatagramsExpected",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["IntArray", "http://soap.zeus.com/zxtm/1.0/", "intArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getUDPTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getUDPTimeout",
      "getUDPTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getUseNagle"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getUseNagle",
      "getUseNagle",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getVirtualServerNames"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getVirtualServerNames",
      "getVirtualServerNames",
      [ ["retval", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getWebcacheControlOut"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getWebcacheControlOut",
      "getWebcacheControlOut",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getWebcacheEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getWebcacheEnabled",
      "getWebcacheEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getWebcacheErrorpageTime"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getWebcacheErrorpageTime",
      "getWebcacheErrorpageTime",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getWebcacheRefreshTime"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getWebcacheRefreshTime",
      "getWebcacheRefreshTime",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "getWebcacheTime"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/getWebcacheTime",
      "getWebcacheTime",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["retval", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeCompressionMIMETypes"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeCompressionMIMETypes",
      "removeCompressionMIMETypes",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeFTPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeFTPPortRange",
      "removeFTPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeRTSPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeRTSPPortRange",
      "removeRTSPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeResponseRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeResponseRules",
      "removeResponseRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "rules", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeRules",
      "removeRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "rules", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeSIPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeSIPPortRange",
      "removeSIPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "removeSSLClientCertificateAuthorities"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/removeSSLClientCertificateAuthorities",
      "removeSSLClientCertificateAuthorities",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "renameVirtualServer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/renameVirtualServer",
      "renameVirtualServer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "new_names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setAddClusterClientIPHeader"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setAddClusterClientIPHeader",
      "setAddClusterClientIPHeader",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setBandwidthClass"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setBandwidthClass",
      "setBandwidthClass",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCompressUnknownSize"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCompressUnknownSize",
      "setCompressUnknownSize",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCompressionEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCompressionEnabled",
      "setCompressionEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCompressionLevel"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCompressionLevel",
      "setCompressionLevel",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCompressionMIMETypes"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCompressionMIMETypes",
      "setCompressionMIMETypes",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCompressionMaxSize"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCompressionMaxSize",
      "setCompressionMaxSize",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCompressionMinSize"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCompressionMinSize",
      "setCompressionMinSize",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setConnectTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setConnectTimeout",
      "setConnectTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCookieDomainRewriteMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCookieDomainRewriteMode",
      "setCookieDomainRewriteMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerCookieDomainRewriteModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.CookieDomainRewriteModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCookieNamedDomain"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCookieNamedDomain",
      "setCookieNamedDomain",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCookiePathRewrite"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCookiePathRewrite",
      "setCookiePathRewrite",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerRegexReplacementArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RegexReplacementArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setCookieSecureFlagRewriteMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setCookieSecureFlagRewriteMode",
      "setCookieSecureFlagRewriteMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerCookieSecureFlagRewriteModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.CookieSecureFlagRewriteModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setDefaultPool"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setDefaultPool",
      "setDefaultPool",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setEnabled",
      "setEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setFTPDataSourcePort"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setFTPDataSourcePort",
      "setFTPDataSourcePort",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setFTPForceClientSecure"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setFTPForceClientSecure",
      "setFTPForceClientSecure",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setFTPForceServerSecure"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setFTPForceServerSecure",
      "setFTPForceServerSecure",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setFTPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setFTPPortRange",
      "setFTPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "range", ["VirtualServerFTPPortRangeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.FTPPortRangeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setFTPSSLData"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setFTPSSLData",
      "setFTPSSLData",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setKeepalive"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setKeepalive",
      "setKeepalive",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setKeepaliveTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setKeepaliveTimeout",
      "setKeepaliveTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setListenAddresses"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setListenAddresses",
      "setListenAddresses",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "addresses", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setListenOnAllAddresses"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setListenOnAllAddresses",
      "setListenOnAllAddresses",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setListenTrafficIPGroups"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setListenTrafficIPGroups",
      "setListenTrafficIPGroups",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "groups", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setLocationDefaultRewriteMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setLocationDefaultRewriteMode",
      "setLocationDefaultRewriteMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerLocationDefaultRewriteModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.LocationDefaultRewriteModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setLocationRewrite"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setLocationRewrite",
      "setLocationRewrite",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerRegexReplacementArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RegexReplacementArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setLogEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setLogEnabled",
      "setLogEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setLogFilename"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setLogFilename",
      "setLogFilename",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setLogFormat"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setLogFormat",
      "setLogFormat",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setMIMEAutoDetect"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setMIMEAutoDetect",
      "setMIMEAutoDetect",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setMIMEDefaultType"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setMIMEDefaultType",
      "setMIMEDefaultType",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setMaxClientBuffer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setMaxClientBuffer",
      "setMaxClientBuffer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setMaxServerBuffer"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setMaxServerBuffer",
      "setMaxServerBuffer",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setPort"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setPort",
      "setPort",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setProtection"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setProtection",
      "setProtection",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setProtocol"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setProtocol",
      "setProtocol",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerProtocolArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.ProtocolArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setProxyClose"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setProxyClose",
      "setProxyClose",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setRTSPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setRTSPPortRange",
      "setRTSPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "range", ["VirtualServerPortRangeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.PortRangeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setResponseRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setResponseRules",
      "setResponseRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "rules", ["VirtualServerRuleArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RuleArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setRewriteSIPURI"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setRewriteSIPURI",
      "setRewriteSIPURI",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setRules"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setRules",
      "setRules",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "rules", ["VirtualServerRuleArrayArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.RuleArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSIPDangerousRequestMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSIPDangerousRequestMode",
      "setSIPDangerousRequestMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerSIPDangerousRequestModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SIPDangerousRequestModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSIPMaxConnectionMemory"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSIPMaxConnectionMemory",
      "setSIPMaxConnectionMemory",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSIPMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSIPMode",
      "setSIPMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerSIPModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SIPModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSIPPortRange"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSIPPortRange",
      "setSIPPortRange",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "range", ["VirtualServerPortRangeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.PortRangeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSIPStreamingTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSIPStreamingTimeout",
      "setSIPStreamingTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLCertificate"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLCertificate",
      "setSSLCertificate",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "certs", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLClientCertificateAuthorities"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLClientCertificateAuthorities",
      "setSSLClientCertificateAuthorities",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArrayArray", "http://soap.zeus.com/zxtm/1.0/", "StringArrayArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLClientCertificateHeaders"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLClientCertificateHeaders",
      "setSSLClientCertificateHeaders",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerSSLClientCertificateHeadersArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLClientCertificateHeadersArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLDecrypt"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLDecrypt",
      "setSSLDecrypt",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLExpectStartTLS"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLExpectStartTLS",
      "setSSLExpectStartTLS",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLHeaders"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLHeaders",
      "setSSLHeaders",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLLogEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLLogEnabled",
      "setSSLLogEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLRequestClientCertMode"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLRequestClientCertMode",
      "setSSLRequestClientCertMode",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["VirtualServerSSLRequestClientCertModeArray", "http://soap.zeus.com/zxtm/1.0/", "VirtualServer.SSLRequestClientCertModeArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLSendCloseAlerts"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLSendCloseAlerts",
      "setSSLSendCloseAlerts",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSSLTrustMagic"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSSLTrustMagic",
      "setSSLTrustMagic",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setServerfirstBanner"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setServerfirstBanner",
      "setServerfirstBanner",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setServiceLevelMonitoring"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setServiceLevelMonitoring",
      "setServiceLevelMonitoring",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setSipTransactionTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setSipTransactionTimeout",
      "setSipTransactionTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setTimeout",
      "setTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setUDPResponseDatagramsExpected"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setUDPResponseDatagramsExpected",
      "setUDPResponseDatagramsExpected",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["IntArray", "http://soap.zeus.com/zxtm/1.0/", "intArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setUDPTimeout"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setUDPTimeout",
      "setUDPTimeout",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setUseNagle"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setUseNagle",
      "setUseNagle",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setWebcacheControlOut"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setWebcacheControlOut",
      "setWebcacheControlOut",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setWebcacheEnabled"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setWebcacheEnabled",
      "setWebcacheEnabled",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["BooleanArray", "http://soap.zeus.com/zxtm/1.0/", "booleanArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setWebcacheErrorpageTime"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setWebcacheErrorpageTime",
      "setWebcacheErrorpageTime",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setWebcacheRefreshTime"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setWebcacheRefreshTime",
      "setWebcacheRefreshTime",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new(NsVirtualServer, "setWebcacheTime"),
      "http://soap.zeus.com/zxtm/1.0/VirtualServer/setWebcacheTime",
      "setWebcacheTime",
      [ ["in", "names", ["StringArray", "http://soap.zeus.com/zxtm/1.0/", "StringArray"]],
        ["in", "values", ["UnsignedIntArray", "http://soap.zeus.com/zxtm/1.0/", "unsignedIntArray"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = VirtualServerMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = VirtualServerMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

